apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kf-api-hpa
spec:
  scaleTagetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kf-api
  minReplicas: 1
  maxReplicas: 10
  targetCPUUUtilizationPercentage: 50
